SUPABASE_URL = "https://kiyovqcllmkmsqsxehzl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeW92cWNsbG1rbXNxc3hlaHpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMzM1NTAsImV4cCI6MjA3NjkwOTU1MH0.1mP3c2M_R-DrNAVDL8CXQ0tn_ojTa7k2WvL9VHYpork"
SUPABASE_BUCKET = "vault_files"
MASTER_ADMIN_KEY = st.secrets.get("ADMINISJACOB9747")
